#cloud-config
users:
  - name: devops
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILGaXFZnIMn5mgxDJUG554QvHQRAGyprmVCUDmG2rTuA aws lab-14

packages:
  - nginx
  - git

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - echo "Welcome to your Terraform VM" > /home/devops/welcome.txt
